### ISSUE TITLE
Error Flutter 3.0.1 (Kotlin version)

### ISSUE THREAD

**Issue by artu-st** [pdliuw/ai_barcode#60]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ai_barcode:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by Aldo-f** [comment]
This should fix it.
https://github.com/pdliuw/ai_barcode/pull/61/commits/b6d98840208c2cf12fddefe5f5ed2f4d8022b9ed 

You can test it out by changing the package (temporarily):
``` yaml
dependencies: 
  # ai_barcode:  ^3.0.1
  ai_barcode:
    git: https://github.com/Aldo-f/ai_barcode.git
```
